language: node_js       #javascript
node_js:
  - stable

env:
  - TRAVIS_TAG="0.1.0" GH_PAGES_DEPLOY_FOLDER=deploy GH_RELEASE_FOLDER=release

cache:
  directories:
    - node_modules

install:
  - npm install -g json-minify
    
script:
  - node ./build-ci/test.js ./recipes.json
  
after_success:
  - echo "Compiling the data into JSON objects and files"
  - node ./build-ci/build_dictionary.js ./recipes.json ./recipes.dictionary.json
  - json-minify ./recipes.json > ./recipes.min.json
  - json-minify ./recipes.dictionary.json > ./recipes.dictionary.min.json
  - echo "Copying files for GH-Pages deployment"
  - mkdir $GH_PAGES_DEPLOY_FOLDER
  - cp recipes.json $GH_PAGES_DEPLOY_FOLDER
  - cp index.html $GH_PAGES_DEPLOY_FOLDER
  - cp LICENSE $GH_PAGES_DEPLOY_FOLDER
  - cp README.md $GH_PAGES_DEPLOY_FOLDER
  - cp ./recipes.json $GH_PAGES_DEPLOY_FOLDER/recipes.json
  - cp ./recipes.min.json $GH_PAGES_DEPLOY_FOLDER/recipes.min.json
  - cp ./recipes.dictionary.json $GH_PAGES_DEPLOY_FOLDER/recipes.dictionary.json
  - cp ./recipes.dictionary.min.json $GH_PAGES_DEPLOY_FOLDER/recipes.dictionary.min.json
  - ls $GH_PAGES_DEPLOY_FOLDER
  - echo "Copying files for GitHub Release deployment to release tag=" $TRAVIS_TAG
  - mkdir $GH_RELEASE_FOLDER
  - cp LICENSE $GH_RELEASE_FOLDER
  - cp README.md $GH_RELEASE_FOLDER
  - cp ./recipes.json $GH_RELEASE_FOLDER/recipes.json
  - cp ./recipes.min.json $GH_RELEASE_FOLDER/recipes.min.json
  - cp ./recipes.dictionary.json $GH_RELEASE_FOLDER/recipes.dictionary.json
  - cp ./recipes.dictionary.min.json $GH_RELEASE_FOLDER/recipes.dictionary.min.json
  - ls $GH_RELEASE_FOLDER
  - echo "Files ready for deployment"




deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  local-dir: $GH_PAGES_DEPLOY_FOLDER
  keep-history: true
  on:
    branch: master
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $GH_RELEASE_FOLDER/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true 
